name: Test Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: puppeter-docker